# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 799571723580a341dd303cc6b6785cea41865695d8ee187f41d0efe6d9f8459fc89706fa5435da857c55d636be66cde200be44e661029d5fcabb70be2e748b93

test:
  secret_key_base: 9873b73c02681f90a1cf9801513a763a78297de59cde5ecf7b6f4b282c123de0a68ac5eb433112af40ab7e1db6fa416390e7113b9143bcf0ba8420262b0d41c8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
