name: reviewdog
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'push'
        run: echo "REPORTER='github-check'" >> $GITHUB_ENV
      - if: github.event_name == 'push'
        run: echo "FILTER='nofilter'" >> $GITHUB_ENV
      - if: github.event_name == 'push'
        run: echo "FAIL='false'" >> $GITHUB_ENV
      - if: github.event_name == 'pull_request'
        run: echo "REPORTER='github-pr-review'" >> $GITHUB_ENV
      - if: github.event_name == 'pull_request'
        run: echo "FILTER='added'" >> $GITHUB_ENV
      - if: github.event_name == 'pull_request'
        run: echo "FAIL='true'" >> $GITHUB_ENV
  rubocop:
    name: rubocop
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
          skip_install: true
          use_bundler: true
          rubocop_flags: --config ./.rubocop.yml
          fail_on_error: ${{ env.FAIL }}
          reporter: ${{ env.REPORTER }}
          filter_mode: ${{ env.FILTER }}
  brakeman:
    name: brakeman
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: 'gemfile'
          fail_on_error: ${{ env.FAIL }}
          reporter: ${{ env.REPORTER }}
          filter_mode: ${{ env.FILTER }}
  haml_lint:
    name: haml-lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
      - uses: reviewdog/action-setup@v1
      - name: haml-lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          bundle exec haml-lint app/views | reviewdog
            -f=haml-lint -name="haml-lint"
            -reporter="${{ env.REPORTER }}"
            -filter_mode=${{ env.FILTER }}
            -fail-on-error=${{ env.FAIL }}
  eslint:
    name: eslint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
      - uses: actions/setup-node@v2
      - run: npm install eslint@~6.0.0
      - uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: 'app/assets/javascripts'
          fail_on_error: ${{ env.FAIL }}
          reporter: ${{ env.REPORTER }}
          filter_mode: ${{ env.FILTER }}
