name: reviewdog
on:
  push:
    branches: [ master ]
jobs:
  reviewdog:
    uses: marri/glowfic/.github/workflows/reviewdog.yml@add/reviewdog
    with:
      reporter: github-check
      filter_mode: nofilter
