name: reviewdog (github-check)
on:
  push:
    branches: [ master ]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
      - uses: reviewdog/action-setup@v1
  rubocop:
    name: rubocop
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
          filter_mode: nofilter
          reporter: github-check
  brakeman:
    name: brakeman
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: 'gemfile'
          filter_mode: nofilter
          reporter: github-check
  haml_lint:
    name: haml-lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: haml-lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: haml-lint app/views | reviewdog -f=haml -name="haml-lint" -reporter="github-check" -filter-mode=nofilter
  eslint:
    name: eslint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - run: npm install eslint@~6.0.0
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          filter_mode: nofilter
          eslint_flags: 'app/assets/javascripts'
