name: reviewdog
on:
  pull_request:
    branches: [ master ]
jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
          skip_install: true
          use_bundler: true
          rubocop_flags: --config ./.rubocop.yml
          fail_on_error: true
          reporter: github-pr-review
  brakeman:
    name: brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
      - name: brakeman
        uses: reviewdog/action-brakeman@v2
        with:
          brakeman_version: 'gemfile'
          fail_on_error: true
          reporter: github-pr-review
  haml_lint:
    name: haml-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
      - uses: reviewdog/action-setup@v1
      - name: haml-lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec haml-lint app/views | reviewdog -f=haml-lint -name="haml-lint" -reporter="github-pr-review" -fail-on-error
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
      - uses: actions/setup-node@v2
      - run: npm install eslint@~6.0.0
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'app/assets/javascripts'
          fail_on_error: true
